// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// multiplier_weights_cpp
NumericMatrix multiplier_weights_cpp(int n, int nboot);
RcppExport SEXP _NonlinearDiD_multiplier_weights_cpp(SEXP nSEXP, SEXP nbootSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type nboot(nbootSEXP);
    rcpp_result_gen = Rcpp::wrap(multiplier_weights_cpp(n, nboot));
    return rcpp_result_gen;
END_RCPP
}
// weighted_mean_cpp
double weighted_mean_cpp(NumericVector x, NumericVector w);
RcppExport SEXP _NonlinearDiD_weighted_mean_cpp(SEXP xSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(weighted_mean_cpp(x, w));
    return rcpp_result_gen;
END_RCPP
}
// dr_score_logit_cpp
NumericVector dr_score_logit_cpp(NumericVector delta_logit, IntegerVector D, NumericVector pscore, NumericVector mu_hat);
RcppExport SEXP _NonlinearDiD_dr_score_logit_cpp(SEXP delta_logitSEXP, SEXP DSEXP, SEXP pscoreSEXP, SEXP mu_hatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type delta_logit(delta_logitSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type D(DSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type pscore(pscoreSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type mu_hat(mu_hatSEXP);
    rcpp_result_gen = Rcpp::wrap(dr_score_logit_cpp(delta_logit, D, pscore, mu_hat));
    return rcpp_result_gen;
END_RCPP
}
// att_from_score_cpp
double att_from_score_cpp(NumericVector score);
RcppExport SEXP _NonlinearDiD_att_from_score_cpp(SEXP scoreSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type score(scoreSEXP);
    rcpp_result_gen = Rcpp::wrap(att_from_score_cpp(score));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_NonlinearDiD_multiplier_weights_cpp", (DL_FUNC) &_NonlinearDiD_multiplier_weights_cpp, 2},
    {"_NonlinearDiD_weighted_mean_cpp", (DL_FUNC) &_NonlinearDiD_weighted_mean_cpp, 2},
    {"_NonlinearDiD_dr_score_logit_cpp", (DL_FUNC) &_NonlinearDiD_dr_score_logit_cpp, 4},
    {"_NonlinearDiD_att_from_score_cpp", (DL_FUNC) &_NonlinearDiD_att_from_score_cpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_NonlinearDiD(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
